import { Head, Link, router, useForm, usePage } from '@inertiajs/react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { WorkspacePanel, WorkspaceSection, Empty, Field, FilterSelect, FormDialog, Pagination, type Paginated, StatusBadge, Toolbar, fieldClass } from '@/components/workspace-ui';
import { AppLayout } from '@/layouts/app-layout';
import type { SharedPageProps } from '@/types';

type Plot = { id: number; plot_code: string; location: string; size: string; status: string; archived_at?: string; assignments_count: number };
export default function GardenPlots({ plots, filters }: { plots: Paginated<Plot>; filters: { search?: string; status?: string } }) {
    const role = usePage<SharedPageProps>().props.auth.user!.role; const operations = role !== 'member'; const [open, setOpen] = useState(false); const [selected,setSelected]=useState<Plot|null>(null);
    const form = useForm({ plot_code: '', location: '', size: '', status: 'available' });
    const save = () => { const options={onSuccess:()=>{setOpen(false);setSelected(null);form.reset();}}; selected?form.put(`/garden-plots/${selected.id}`,options):form.post('/garden-plots',options); };
    const edit=(p?:Plot)=>{form.clearErrors();setSelected(p??null);form.setData({plot_code:p?.plot_code??'',location:p?.location??'',size:p?.size??'',status:p?.status??'available'});setOpen(true)};
    return <><Head title="Garden plots" /><AppLayout title="Garden plots" description="Browse availability and manage the garden’s plots." actions={<div className="flex flex-wrap items-center gap-2"><Button asChild variant="outline" size="sm"><Link href="/garden-plots">Browse plots</Link></Button><Toolbar path="/garden-plots" search={filters.search} actionLabel={operations ? 'New plot' : undefined} onAction={() => edit()} /></div>}>
        <div className="space-y-8 pb-9"><WorkspaceSection title="Garden plots" description={`${plots.total} plots matching the current filters.`} actions={<FilterSelect label="Status" value={filters.status} options={['available','reserved','occupied','maintenance','archived'].map(v => [v,v])} onChange={(status) => router.get('/garden-plots', { view: 'manage', ...filters, status }, { preserveState: true })} />}>
        {plots.data.length === 0 ? <Empty message="No plots match these filters." /> : <WorkspacePanel><Table><TableHeader><TableRow className="hover:bg-transparent"><TableHead>Plot</TableHead><TableHead>Location</TableHead><TableHead>Area</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{plots.data.map(p => <TableRow key={p.id}><TableCell className="font-semibold">{p.plot_code}</TableCell><TableCell>{p.location}</TableCell><TableCell>{p.size} m²</TableCell><TableCell><StatusBadge value={p.archived_at?'archived':p.status} /></TableCell><TableCell className="space-x-1 text-right">{role === 'member' && p.status === 'available' && !p.archived_at && <Button size="sm" variant="outline" onClick={() => router.post('/plot-requests', { garden_plot_id: p.id })}>Request plot</Button>}{operations && !p.archived_at && <><Button size="sm" variant="outline" onClick={()=>edit(p)}>Edit</Button><Button size="sm" variant="ghost" onClick={() => window.confirm('Archive this plot?')&&router.post(`/garden-plots/${p.id}/archive`)}>Archive</Button></>}</TableCell></TableRow>)}</TableBody></Table><Pagination page={plots} /></WorkspacePanel>}
    </WorkspaceSection></div>
    </AppLayout><FormDialog open={open} onOpenChange={setOpen} title={selected?'Edit garden plot':'Create garden plot'} description="Keep plot inventory and availability accurate." processing={form.processing} onSubmit={save}><Field label="Plot code" error={form.errors.plot_code}><input className={fieldClass} value={form.data.plot_code} onChange={e => form.setData('plot_code', e.target.value)} /></Field><Field label="Location" error={form.errors.location}><input className={fieldClass} value={form.data.location} onChange={e => form.setData('location', e.target.value)} /></Field><Field label="Area (m²)" error={form.errors.size}><input className={fieldClass} type="number" step="0.01" value={form.data.size} onChange={e => form.setData('size', e.target.value)} /></Field><Field label="Status" error={form.errors.status}><select className={fieldClass} value={form.data.status} onChange={e=>form.setData('status',e.target.value)}>{['available','reserved','occupied','maintenance'].map(x=><option key={x} disabled={x==='occupied'&&selected?.status!=='occupied'}>{x}</option>)}</select></Field></FormDialog></>;
}
