import { Head, router, useForm, usePage } from '@inertiajs/react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Empty, Field, FilterSelect, FormDialog, Pagination, type Paginated, StatusBadge, Toolbar, fieldClass, textareaClass } from '@/components/workspace-ui';
import { AppLayout } from '@/layouts/app-layout';
import type { SharedPageProps } from '@/types';
type RequestItem = { id:number; status:string; notes?:string; decision_notes?:string; created_at:string; user:{name:string}; garden_plot?:{id:number;plot_code:string;location:string} };
type Plot = {id:number;plot_code:string;location:string};
export default function PlotRequests({ requests, availablePlots, filters }: {requests:Paginated<RequestItem>;availablePlots:Plot[];filters:{search?:string;status?:string}}) {
 const role=usePage<SharedPageProps>().props.auth.user!.role; const member=role==='member'; const [mode,setMode]=useState<'new'|'approve'|'reject'|null>(null); const [selected,setSelected]=useState<RequestItem|null>(null);
 const form=useForm({garden_plot_id:'',notes:'',start_date:new Date().toISOString().slice(0,10),end_date:'',decision_notes:''});
 const act=()=>{ if(mode==='new') form.post('/plot-requests',{onSuccess:()=>setMode(null)}); else if(selected) form.post(`/plot-requests/${selected.id}/${mode}`,{onSuccess:()=>setMode(null)}); };
 return <><Head title={member?'My plot requests':'Plot requests'}/><AppLayout title={member?'My plot requests':'Plot requests'} description={member?'Submit and track requests for a garden plot.':'Review member requests and create assignments.'} actions={<Toolbar path="/plot-requests" search={filters.search} filters={<FilterSelect label="Status" value={filters.status} options={['pending','approved','rejected','cancelled'].map(v=>[v,v])} onChange={status=>router.get('/plot-requests',{...filters,status},{preserveState:true})}/>} actionLabel={member?'New request':undefined} onAction={()=>{form.reset();setMode('new')}}/>}>
 {requests.data.length===0?<Empty message="No plot requests found."/>:<Card className="overflow-hidden"><Table><TableHeader><TableRow>{!member&&<TableHead>Member</TableHead>}<TableHead>Plot</TableHead><TableHead>Submitted</TableHead><TableHead>Status</TableHead><TableHead>Notes</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{requests.data.map(item=><TableRow key={item.id}>{!member&&<TableCell className="font-medium">{item.user.name}</TableCell>}<TableCell>{item.garden_plot?.plot_code??'Any plot'}</TableCell><TableCell>{new Date(item.created_at).toLocaleDateString()}</TableCell><TableCell><StatusBadge value={item.status}/></TableCell><TableCell className="max-w-56 truncate">{item.decision_notes??item.notes??'—'}</TableCell><TableCell className="text-right space-x-1">{member&&item.status==='pending'&&<Button variant="outline" size="sm" onClick={()=>router.post(`/plot-requests/${item.id}/cancel`)}>Cancel</Button>}{!member&&item.status==='pending'&&<><Button size="sm" onClick={()=>{setSelected(item);form.reset();setMode('approve')}}>Approve</Button><Button size="sm" variant="outline" onClick={()=>{setSelected(item);form.reset();setMode('reject')}}>Reject</Button></>}</TableCell></TableRow>)}</TableBody></Table><Pagination page={requests}/></Card>}
 </AppLayout><FormDialog open={mode!==null} onOpenChange={v=>!v&&setMode(null)} title={mode==='new'?'Request a plot':mode==='approve'?'Approve request':'Reject request'} description={mode==='new'?'Choose an available plot and tell the team anything relevant.':mode==='approve'?'This immediately creates an active assignment.':'Explain the decision to the member.'} submitLabel={mode==='approve'?'Approve and assign':mode==='reject'?'Reject request':'Submit request'} processing={form.processing} onSubmit={act}>
 {mode==='new'&&<><Field label="Available plot" error={form.errors.garden_plot_id}><select className={fieldClass} value={form.data.garden_plot_id} onChange={e=>form.setData('garden_plot_id',e.target.value)}><option value="">Select a plot</option>{availablePlots.map(p=><option value={p.id} key={p.id}>{p.plot_code} — {p.location}</option>)}</select></Field><Field label="Notes" error={form.errors.notes}><textarea className={textareaClass} value={form.data.notes} onChange={e=>form.setData('notes',e.target.value)}/></Field></>}
 {mode==='approve'&&<><Field label="Start date" error={form.errors.start_date}><input type="date" className={fieldClass} value={form.data.start_date} onChange={e=>form.setData('start_date',e.target.value)}/></Field><Field label="End date (optional)" error={form.errors.end_date}><input type="date" className={fieldClass} value={form.data.end_date} onChange={e=>form.setData('end_date',e.target.value)}/></Field></>}
 {(mode==='approve'||mode==='reject')&&<Field label={mode==='reject'?'Reason':'Decision note (optional)'} error={form.errors.decision_notes}><textarea className={textareaClass} value={form.data.decision_notes} onChange={e=>form.setData('decision_notes',e.target.value)}/></Field>}
 </FormDialog></>;
}
